name: kafka-cluster-kraft

services:
  controller-1:
    image: 'bitnami/kafka:latest'
    container_name: controller-1
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CLUSTER_ID=cCFL_1dBRymfT3c4mlNMYw
      - KAFKA_CFG_PROCESS_ROLES=controller
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller-1:9093,2@controller-2:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INITIAL_CONTROLLERS=

  controller-2:
    image: 'bitnami/kafka:latest'
    container_name: controller-2
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CLUSTER_ID=cCFL_1dBRymfT3c4mlNMYw
      - KAFKA_CFG_PROCESS_ROLES=controller
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller-1:9093,2@controller-2:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

  broker-1:
    image: 'bitnami/kafka:latest'
    container_name: broker-1
    ports:
      - 9094:9094
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_CLUSTER_ID=cCFL_1dBRymfT3c4mlNMYw
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19094,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-1:19094,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller-1:9093,2@controller-2:9093
      - BITNAMI_DEBUG=true
    depends_on:
      - controller-1
      - controller-2

  broker-2:
    image: 'bitnami/kafka:latest'
    container_name: broker-2
    ports:
      - 9095:9095
    environment:
      - KAFKA_NODE_ID=4
      - KAFKA_CLUSTER_ID=cCFL_1dBRymfT3c4mlNMYw
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29095,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-2:29095,EXTERNAL://localhost:9095
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller-1:9093,2@controller-2:9093
      - BITNAMI_DEBUG=true
    depends_on:
      - controller-1
      - controller-2

  broker-3:
    image: 'bitnami/kafka:latest'
    container_name: broker-3
    ports:
      - 9096:9096
    environment:
      - KAFKA_NODE_ID=5
      - KAFKA_CLUSTER_ID=cCFL_1dBRymfT3c4mlNMYw
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:39096,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-3:39096,EXTERNAL://localhost:9096
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@controller-1:9093,2@controller-2:9093
      - BITNAMI_DEBUG=true
    depends_on:
      - controller-1
      - controller-2

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:19094,broker-2:29095,broker-3:39096
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      